module.exports = {
    user:[
        {account:'admin',name:'admin',password:'admin',type:1}
    ],
    msg:[
        {title:'test',type:1,content:'<p>test</p>'},
        {title:'test',type:1,content:'<p>test</p>'},
        {title:'test',type:1,content:'<p>test</p>'},
        {title:'test',type:1,content:'<p>test</p>'},
        {title:'test',type:1,content:'<p>test</p>'},
        {title:'test',type:1,content:'<p>test</p>'},
        {title:'test',type:1,content:'<p>test</p>'},
        {title:'test',type:1,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'},
        {title:'test',type:2,content:'<p>test</p>'}
    ],
    dictionary:[
        {code:1,name:'公司公告',value:'1',description:'公司公告'},
        {code:1,name:'媒体报道',value:'2',description:'公司公告'}
    ]
}